hajimari:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/enable: 'false'
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
        - host: home.192-168-0-200.nip.io
          paths:
            - path: /
              pathType: Prefix
