source:
  repoUrl: https://github.com/erykio/k3s-virtualbox.git
  revision: master

apps:
  - appName: metallb
    path: cluster/apps/metallb
    namespace: metallb-system
  - appName: ingress-nginx
    path: cluster/apps/ingress-nginx
    namespace: ingress-nginx
  - appName: hajimari
    path: cluster/apps/hajimari
    namespace: hajimari
  - appName: kuard
    path: cluster/apps/kuard
    namespace: kuard
  - appName: nginx-demo
    path: cluster/apps/nginx-demo
    namespace: nginx-demo