{{- range $index, $app := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.appName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # when Application is deleted, its resources will also be deleted
spec:
  project: default # TODO
  source:
    repoURL: {{ $.Values.source.repoUrl }}
    targetRevision: {{ $.Values.source.revision }}
    path: {{ $app.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}